import { Theme } from "./theme";

export interface ThemeTemplate extends Theme {
  layout: "frame" | "band" | "centered" | "sidebar" | "split";
}

export const extraThemes: ThemeTemplate[] = [
  {
    id: "emerald-garden",
    name: "Emerald Garden",
    description: "Opulent emerald and gold with artistic paisley corners",
    layout: "frame",
    swatch: ["#0f4a3c", "#c9a227", "#f4f7f0"],
    bg: "#f4f7f0",
    text: "#1c2e27",
    primary: "#0f4a3c",
    secondary: "#7a6a2a",
    border: "#c9a227",
    headingFont: "'Playfair Display', 'Noto Serif Devanagari', serif",
    bodyFont: "'Cormorant Garamond', 'Noto Serif Devanagari', serif",
    photoShape: "rect",
    corner: "paisley",
  },
  {
    id: "midnight-gold",
    name: "Midnight Gold",
    description: "A polished charcoal band with rich golden accents",
    layout: "band",
    swatch: ["#14161c", "#d4af37", "#ffffff"],
    bg: "#ffffff",
    text: "#1a1a1a",
    primary: "#14161c",
    secondary: "#d4af37",
    border: "#e6e1d3",
    headingFont: "'Cinzel', 'Noto Serif Devanagari', serif",
    bodyFont: "'EB Garamond', 'Noto Serif Devanagari', serif",
    photoShape: "rounded",
    corner: "none",
  },
  {
    id: "sunset-peach",
    name: "Sunset Peach",
    description: "Warm peach and coral tones with a welcoming center focus",
    layout: "centered",
    swatch: ["#e07a5f", "#f2cc8f", "#fff8f2"],
    bg: "#fff8f2",
    text: "#5a3b2e",
    primary: "#e07a5f",
    secondary: "#c98a55",
    border: "#f2cc8f",
    headingFont: "'Playfair Display', 'Noto Serif Devanagari', serif",
    bodyFont: "'Cormorant Garamond', 'Noto Serif Devanagari', serif",
    photoShape: "circle",
    corner: "dots",
  },
  {
    id: "ivory-lace",
    name: "Ivory Lace",
    description: "Soft ivory and silver with delicate diamond detailing",
    layout: "frame",
    swatch: ["#8a8578", "#c7c2b3", "#fffdf7"],
    bg: "#fffdf7",
    text: "#3c3a33",
    primary: "#8a8578",
    secondary: "#9c8e6a",
    border: "#c7c2b3",
    headingFont: "'Source Serif 4', 'Noto Serif Devanagari', serif",
    bodyFont: "'Lora', 'Noto Serif Devanagari', serif",
    photoShape: "rounded",
    corner: "diamonds",
  },
  {
    id: "teal-bloom",
    name: "Teal Bloom",
    description: "Fresh teal styling with a confident modern sidebar",
    layout: "sidebar",
    swatch: ["#0f5c5c", "#38a3a5", "#ffffff"],
    bg: "#ffffff",
    text: "#1c2b2b",
    primary: "#0f5c5c",
    secondary: "#38a3a5",
    border: "#e3ecec",
    headingFont: "'Poppins', 'Noto Sans Devanagari', sans-serif",
    bodyFont: "'Inter', 'Noto Sans Devanagari', sans-serif",
    photoShape: "rect",
    corner: "none",
  },
  {
    id: "crimson-regal",
    name: "Crimson Regal",
    description: "Bold crimson and gold with an ornate festive frame",
    layout: "frame",
    swatch: ["#8c1c2b", "#d9a441", "#fdf6ec"],
    bg: "#fdf6ec",
    text: "#3a1414",
    primary: "#8c1c2b",
    secondary: "#a3762a",
    border: "#d9a441",
    headingFont: "'Playfair Display', 'Noto Serif Devanagari', serif",
    bodyFont: "'Cormorant Garamond', 'Noto Serif Devanagari', serif",
    photoShape: "rect",
    corner: "paisley",
  },
  {
    id: "sage-simplicity",
    name: "Sage Simplicity",
    description: "Muted sage tones with an understated modern sidebar",
    layout: "sidebar",
    swatch: ["#5b6b4f", "#a3b18a", "#fbfbf8"],
    bg: "#fbfbf8",
    text: "#2c2f27",
    primary: "#5b6b4f",
    secondary: "#8a9678",
    border: "#e6e6dd",
    headingFont: "'Poppins', 'Noto Sans Devanagari', sans-serif",
    bodyFont: "'Inter', 'Noto Sans Devanagari', sans-serif",
    photoShape: "rounded",
    corner: "none",
  },
  {
    id: "lavender-dream",
    name: "Lavender Dream",
    description: "Soft lavender romance in a balanced centered layout",
    layout: "centered",
    swatch: ["#7b6a9e", "#c9b6e4", "#faf8fd"],
    bg: "#faf8fd",
    text: "#40365a",
    primary: "#7b6a9e",
    secondary: "#9a86bd",
    border: "#dfd2f0",
    headingFont: "'Playfair Display', 'Noto Serif Devanagari', serif",
    bodyFont: "'Cormorant Garamond', 'Noto Serif Devanagari', serif",
    photoShape: "circle",
    corner: "dots",
  },
  {
    id: "charcoal-professional",
    name: "Charcoal Professional",
    description: "Steel blue and charcoal with a clean professional finish",
    layout: "band",
    swatch: ["#2b2f38", "#4a6fa5", "#ffffff"],
    bg: "#ffffff",
    text: "#1f2229",
    primary: "#2b2f38",
    secondary: "#4a6fa5",
    border: "#e2e4e8",
    headingFont: "'Source Serif 4', 'Noto Serif Devanagari', serif",
    bodyFont: "'Inter', 'Noto Sans Devanagari', sans-serif",
    photoShape: "rect",
    corner: "none",
  },
  {
    id: "marigold-festive",
    name: "Marigold Festive",
    description: "Joyful marigold orange tones in a bright split layout",
    layout: "split",
    swatch: ["#c9660b", "#f2b134", "#fff9ef"],
    bg: "#fff9ef",
    text: "#4a2e10",
    primary: "#c9660b",
    secondary: "#a85f1c",
    border: "#fbe4b8",
    headingFont: "'Playfair Display', 'Noto Serif Devanagari', serif",
    bodyFont: "'Cormorant Garamond', 'Noto Serif Devanagari', serif",
    photoShape: "rounded",
    corner: "diamonds",
  },
  {
    id: "rosewood-heritage",
    name: "Rosewood Heritage",
    description: "Warm rosewood, antique gold, and a refined heritage frame",
    layout: "frame",
    swatch: ["#6b2737", "#c69c6d", "#fbf4e8"],
    bg: "#fbf4e8",
    text: "#321f24",
    primary: "#6b2737",
    secondary: "#986b4d",
    border: "#c69c6d",
    headingFont: "'Playfair Display', 'Noto Serif Devanagari', serif",
    bodyFont: "'Lora', 'Noto Serif Devanagari', serif",
    photoShape: "rect",
    corner: "diamonds",
  },
  {
    id: "ocean-pearl",
    name: "Ocean Pearl",
    description: "Airy blue-green tones with a calm circular profile layout",
    layout: "centered",
    swatch: ["#176b87", "#8fc9c3", "#f3fbfa"],
    bg: "#f3fbfa",
    text: "#173c48",
    primary: "#176b87",
    secondary: "#4f8f91",
    border: "#b9ded9",
    headingFont: "'Source Serif 4', 'Noto Serif Devanagari', serif",
    bodyFont: "'Inter', 'Noto Sans Devanagari', sans-serif",
    photoShape: "circle",
    corner: "dots",
  },
  {
    id: "terracotta-mosaic",
    name: "Terracotta Mosaic",
    description: "Earthy terracotta and saffron accents in a lively split layout",
    layout: "split",
    swatch: ["#a84f35", "#e2a23b", "#fff7ed"],
    bg: "#fff7ed",
    text: "#49251c",
    primary: "#a84f35",
    secondary: "#9a6a35",
    border: "#edc98f",
    headingFont: "'Cormorant Garamond', 'Noto Serif Devanagari', serif",
    bodyFont: "'Inter', 'Noto Sans Devanagari', sans-serif",
    photoShape: "rounded",
    corner: "diamonds",
  },
  {
    id: "pine-ink",
    name: "Pine Ink",
    description: "Deep pine, parchment, and soft copper in a modern sidebar",
    layout: "sidebar",
    swatch: ["#23483d", "#b77b52", "#f7f6ef"],
    bg: "#f7f6ef",
    text: "#26352f",
    primary: "#23483d",
    secondary: "#8d765f",
    border: "#d9d6c9",
    headingFont: "'Cinzel', 'Noto Serif Devanagari', serif",
    bodyFont: "'Inter', 'Noto Sans Devanagari', sans-serif",
    photoShape: "rounded",
    corner: "none",
  },
  {
    id: "sapphire-saffron",
    name: "Sapphire Saffron",
    description: "Confident sapphire with saffron highlights and a polished band",
    layout: "band",
    swatch: ["#164e63", "#e5a83b", "#f8fbfc"],
    bg: "#f8fbfc",
    text: "#18313c",
    primary: "#164e63",
    secondary: "#a16f25",
    border: "#c7dce2",
    headingFont: "'Playfair Display', 'Noto Serif Devanagari', serif",
    bodyFont: "'Inter', 'Noto Sans Devanagari', sans-serif",
    photoShape: "rect",
    corner: "none",
  },
];
